# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SMB1355_SLAVE_CHARGER_SDM845)	+= smb1355-charger.o pmic-voter.o
obj-$(CONFIG_QPNP_SMB2_SDM845)			+= step-chg-jeita.o battery.o qpnp-smb2.o smb-lib.o pmic-voter.o storm-watch.o
obj-$(CONFIG_QPNP_FG_GEN3_SDM845)		+= qpnp-fg-gen3.o fg-memif.o fg-util.o
